server:
  port: 9091

spring:
  datasource:
    url: jdbc:h2:mem:employee-db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      data-locations: classpath:stored-proc.sql
    script:
      encoding: UTF-8

  h2:
    console:
      enabled: true
      path: /h2-console
